if(APPLE)
    find_path(LIBXML2_INCLUDE_DIR NAMES "libxml/xmlwriter.h" PATHS ${CONAN_INCLUDE_DIRS_LIBXML2} PATH_SUFFIXES libxml2)
else()
    find_path(LIBXML2_INCLUDE_DIR NAMES "libxml/xmlwriter.h" PATHS ${CONAN_INCLUDE_DIRS_LIBXML2})
endif()
message(STATUS "Look for ${CONAN_LIBS_LIBXML2} in ${CONAN_LIB_DIRS_LIBXML2}")
find_library(LIBXML2_LIBRARY NAMES ${CONAN_LIBS_LIBXML2} PATHS ${CONAN_LIB_DIRS_LIBXML2})

message("** libxml2 already found by conan!")
SET(LIBXML2_FOUND TRUE)
message(STATUS "** Found libxml2:  ${LIBXML2_LIBRARY}")
message(STATUS "** Found libxml2 include:  ${LIBXML2_INCLUDE_DIR}")

set(LIBXML2_INCLUDE_DIRS ${LIBXML2_INCLUDE_DIR})
set(LIBXML2_LIBRARIES ${LIBXML2_LIBRARY})

mark_as_advanced(LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
